### ISSUE TITLE
Asset management for LESS/SCSS...

### ISSUE THREAD

**Issue by Torann** [catberry/catberry#149]
Are there any plans to support some type of asset management for Catberry such as Gulp? Or am I missing something, is there already something in place for this?

I found this [commit](https://github.com/catberry/catberry/commit/201d9207a3d27348b5074eaa509c99c0d6ff0ae7) that talks of asset but it doesn't seem to support LESS or SCSS

**Comment by pragmadash** [comment]
Catberry does not include Gulp, preprocessors and other stuff for assets. It just copies assets from components to `./public/assets` directory and minifies the code of the application.

But if you want to have Gulp tasks that do something for you, please take a look at [csstime](https://github.com/csstime/csstime-gulp-tasks) library. It was developed especially for Catberry applications.

**Comment by markuplab** [comment]
@Torann i think, best way to assign assets is cat-component.json. Now i working on webpack integration, and write module-preloader that parse cat-component.json and append requires for assets in module. After this you can use webpack loaders such a css-loader or less-loader.

```
// before preloader or in node.js
module.exports = Component;

function Component() {
   ...
}

// after preloader
require('./styles.less');

module.exports = Component;

function Component() {
   ...
}
```

I don't know when i end this, and don't know @pragmadash is accept it, but i don't think it's takes long time. __Sorry for bad english__ :smiley:

**Comment by Torann** [comment]
@markuplab Thanks, I'll look into it

**Comment by pragmadash** [comment]
@Torann In my plans to integrate [csstime](https://github.com/csstime/csstime-gulp-tasks) into Carberry's 5.0 release. It will be a plugin which receives paths of all components and built their assets using Gulp. Watch will be able to work in incremental way, not just rebuilding everything on every change.

**Comment by ivancevich** [comment]
This is something I'd really like to have. @pragmadash: what do you think is the roadmap for 5.0?
I'm about to start a new project using Catberry, and this feature would be a killer one!

**Comment by pragmadash** [comment]
@ivancevich So, I'll be working on it the whole next week. I think the next weekend we can call the "deadline". I'll do my best to finish it by the weekend, but I can't promise anything, I have a lot of work nowadays.

[Here](https://github.com/catberry/catberry/milestones/Catberry%205.0) is a ling to the milestone.

**Comment by ivancevich** [comment]
Cool @pragmadash!
If there is something I can help with, I'll happy to do it.
Please, let me know if you need a hand.

**Comment by Torann** [comment]
This is great! :smile:

**Comment by ivancevich** [comment]
@pragmadash have you seen this? https://github.com/js-next/react-style
Maybe we can apply some similar concepts...

**Comment by pragmadash** [comment]
@ivancevich I don't think that it's a good approach. The styles should be in separate style files, not in the JavaScript code. Another reason, a lot of people use LESS, SASS, SCSS and even this issue is about LESS/SCSS.

So, seems like I need to tell more about how it will work.

We still will publish our assets for every component in `assets` directory inside the component's directory. Now all assets are just copied to a public folder. But in next release Catberry will be collecting all paths to `assets` directories and pass them to a special plugin based on [csstime](https://github.com/csstime/csstime-gulp-tasks). This plugin has its own configuration (it will be a Carberry's config section called `assets`) and it uses Gulp and its tasks to deal with a majority of kinds of assets, like graphics, styles and so on. Also, in a debug mode it will use `gulp-watch` and `gulp-changed` and rebuild only the changed stuff.

In fact, new assets plugin will be building style.css file in a public directory, minifying and processing other components' assets moving the processed versions to a public directory by folders with names of the components.

**Comment by pragmadash** [comment]
Hi, the main part of Catberry 5.0 release is finished!
https://github.com/catberry/catberry/pull/156
But I didn't have enough time to finish new assets management plugin, seems like I'll delay release for 2-3 days.

Keep in touch!

**Comment by pragmadash** [comment]
Added as a plugin https://www.npmjs.com/package/catberry-assets for [Catberry 5.0](https://github.com/catberry/catberry/releases/tag/5.0.0).

**Comment by Torann** [comment]
Thanks

**Comment by pragmadash** [comment]
@Torann You're welcome!
