### ISSUE TITLE
Implement browsersync into `npm run debug`

### ISSUE THREAD

**Issue by MickCoelho** [catberry/catberry#161]
Would be interesting to get live-reload included into the starting templates.

**Comment by pragmadash** [comment]
I think that it's not a good idea to include [browsersync](http://www.browsersync.io/) into the project template. It has the huge and heavy dependency graph which will dramatically slow the `npm install` process. So, you can use it in proxy mode separately like it's described in the [documentation](http://www.browsersync.io/docs/command-line/#proxy-example).

If we speak about implementing browsersync-like engine for Catberry, in my opinion it does not make any sense because it's not the easiest thing to implement and there is a browsersync proxy mode already which any user is able to use with Catberry.
