### ISSUE TITLE
Is Catberry really fast?

### ISSUE THREAD

**Issue by frol** [catberry/catberry#168]
> Fast and efficient server-side progressive rendering engine based on node.js streams
> ...
> Thanks to Catberry's very fast page rendering engine, user receives refreshed page as fast as API server could provide data for it.

I'm new to JS server-side development and I have never tried to benchmark it before. This time I wanted to try to build my first JS isomorphic app. Thus, I checked different available frameworks and Catberry claimed to be "fast", so I started with it... I took este.js as another isomorphic framework and setup TodoMVC examples for both frameworks. Here are the results that I got with `siege -t 1m -c 500 -b http://127.0.0.1:3000` on io.js v2.2.1 on my Core i7 (io.js loaded one core):

**Catberry: 42.42 trans/sec**

**Este.js: 165.55 trans/sec**

I have started Catberry-todomvc with `npm start` and Este.js with `gulp -p`. Have I done something wrong or Catberry is not that fast?

Full siege report for Catberry:

```
Transactions:                   2520 hits
Availability:                 100.00 %
Elapsed time:                  59.40 secs
Data transferred:               8.14 MB
Response time:                  9.40 secs
Transaction rate:              42.42 trans/sec
Throughput:                     0.14 MB/sec
Concurrency:                  398.97
Successful transactions:        2520
Failed transactions:               0
Longest transaction:           43.19
Shortest transaction:           0.04
```

Full siege report for Este.js:

```
Transactions:                   9918 hits
Availability:                 100.00 %
Elapsed time:                  59.91 secs
Data transferred:              10.24 MB
Response time:                  1.63 secs
Transaction rate:             165.55 trans/sec
Throughput:                     0.17 MB/sec
Concurrency:                  269.79
Successful transactions:        9918
Failed transactions:               0
Longest transaction:           19.16
Shortest transaction:           0.08
```

Just pointless results:

Hello-world on pure io.js (`require("http")`): 3469.60 trans/sec

Hello-world on Expressjs: 2324.17 trans/sec

Edited by @pragmadash.
**Update**:
https://github.com/catberry/catberry-benchmarks – the benchmark shows that Catberry has almost the same performance as bare Express with the same template engine.

**Comment by pragmadash** [comment]
You just missed the point what progressive rendering is. If blocks of the page you are rendering need data from the remote resource (i.e database or RESTful API) it will be real fast for a user. This is because first parts of the page are seen by a user almost immediately with a minimal delay. Also, as far as it uses fully asynchronous and non-blocking algorithms it is very concurrent-friendly at the server and don't freeze the UI in a browser.

So, in real applications with plenty of data from the remote sources Catberry **looks dramatically faster for a user** but maybe in synthetic benchmarks like you provided with it could look like an outsider. But we can't compare the full-buffering rendering and progressive rendering, it's like comparing hot and tasty.
In the first case using full-buffering rendering engine like Este.js has the user does not see anything until the whole page will be ready. And if you data source isn't so fast like you web UI it will be an awful user experience. But if you use the progressive rendering engine with streaming the user will see the first part of the page as soon as first bytes of the main template are rendered even if no data was loaded. 

Here is an image which explains the main idea of the progressive rendering
![progressive-rendering](https://cloud.githubusercontent.com/assets/887952/8028253/aea70836-0dc2-11e5-831b-eaa0e9cba2d9.png)

Also, there is an advantage of using such approach – loading resources concurrently if they were defined at the beginning of the page.
![network](https://cloud.githubusercontent.com/assets/887952/8028257/d866e0ba-0dc2-11e5-90f1-8487dd697452.png)

So, it's up to you. Would you like to have great numbers in benchmarks or satisfied users of your web-application? I choose the second one.

If you want to see the power of the Catberry's rendering engine you should render the huge page divided in blocks that load data from different remote resources. In this case, you'll see the difference in a browser and especially in network timeline.

If you don't want to implement such an example, you can visit [Flamp](http://flamp.ru/best) and see the progressive rendering there. We have 20 million views and 12 million unique visitors per month on this project and still don't have a big CPU or memory load on Catberry application's processes.

**Comment by frol** [comment]
@pragmadash Thank you for such a complete answer! I haven't missed the point of progressive rendering. I've read some parts of documentation, especially those parts that are related to speed. I've also watched your recent speech at Enterra. However, what I see on Flamp web-site is that it takes 3-4 seconds to load the page completely (but I admit that from user point of view it doesn't feel like just waiting 3-4 seconds for nothing), and it also doesn't use cache for style.css, bundle.js, and many more other resources. But according to my benchmark it seems that 3-4 seconds with Catberry is "equal" to 0.5 - 0.7 seconds on Este.js (approximation is based on average response time from my benchmark) and with proper resource caching it will take, lets say, 1 second to load full page, but with Catberry my browser requests for css and js only on 1.25 second after the main request is started and (without cache) finishes their load on 1.75 (css) - 2.05 (js) seconds.

My point is not to discredit the awesome Catberry, but to understand limits better!

Is there a room for optimizations in Catberry?

**Comment by pragmadash** [comment]
"Flamp web-site is that it takes 3-4 seconds to load the page completely"
Because the API delivers data with such delays, these requests for data are very "heavy". Therefore if we didn't use progressive rendering here it would be 4 seconds of showing "white page" to the user until all data is ready.

"and it also doesn't use cache for style.css, bundle.js, and many more other resources"
It does, using ETag and conditional requests from a browser. Are you sure you didn't switch off the cache in browser's DevTools?

"but with Catberry my browser requests for css and js only on 1.25 second after the main request is started"
Could you post here a network timeline?
That's really strange, maybe it's related to Express `servestatic` module, connection count limitations in a browser, the delay to Russia networks and so on. BTW we have just 2 node.js processes serving this application. Maybe `servestatic` is not good in concurrency, I don't know. It could be plenty of reasons.

"Is there a room for optimizations in Catberry?"
Frankly speaking, I didn't work on rendering optimizations in Catberry so far because I didn't have any complaints from developers or users. But your help is welcome, for sure! The entire rendering system is concentrated in these files:
* https://github.com/catberry/catberry/blob/develop/lib/streams/ComponentReadable.js
* https://github.com/catberry/catberry/blob/develop/lib/streams/ComponentTransform.js
* https://github.com/catberry/catberry/blob/develop/lib/streams/ResponseTransform.js

**Comment by frol** [comment]
![flamp_network](https://cloud.githubusercontent.com/assets/304265/8029304/9900cecc-0dcc-11e5-83f1-9810d4b4d329.png)

As you can see, cache is not disabled, and here is what the response is:

```http
Cache-Control:public, max-age=0
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/javascript; charset=utf-8
Date:Mon, 08 Jun 2015 06:49:58 GMT
Server:nginx
Transfer-Encoding:chunked
X-Powered-By:Express
```

**Comment by pragmadash** [comment]
The green parts could be also network delays. But the picture, in general, is normal in my opinion, you have a lot of concurrent requests for resources during the page is loading.

About these caching headers, you are right, thank you for the report but it's related to our NGINX configuration, not the Catberry application, I checked the application locally and it has ETag headers. Apparently they are cut somehow by NGINX, we didn't have such problem before we will investigate the issue.

**Comment by frol** [comment]
@pragmadash Yes, it is not bad by any means. I will continue playing with Catberry, Este.js, and, probably, some other projects, just because they are very different and I'm not sure yet what I need. For example, Este.js uses babeljs, so I can write ES6/7 code. Is it something that is easy to add to Catberry if I need it?

I've read "advantages" section on Catberry main page, but are there strong disadvantages? :)

**Comment by pragmadash** [comment]
> Is it something that is easy to add to Catberry if I need it?

As far as I didn't try, I can't say anything about it by the moment. But there is a [Plugin API](http://catberry.org/documentation#plugin-api) which should help .

> I've read "advantages" section on Catberry main page, but are there strong disadvantages? :)

If I knew any, I would have fixed them already :) So, let me know if you find one.

**Comment by pragmadash** [comment]
@frol I did some research on Catberry's server-side performance, please take a look https://github.com/catberry/catberry-benchmarks.

According my results it has almost the same performance as bare Express with the same template engine.

So, maybe you didn't turn off log messages during your tests or maybe Este.js todomvc page was the static one or cache was used. I can't explain your results, but these tests I did are fair in my opinion.

Also, feel free to fork and add your own benchmarks to the repository or let me know if you find any errors in the benchmark.
