### ISSUE TITLE
webkitMovementX / webkitMovementY is deprecated

### ISSUE THREAD

**Issue by wormen** [catberry/catberry#197]
After the next update the browser began to appear alert
this is the latest version of Google chrome
https://yadi.sk/i/Qx-vUpqwitCdM

**Comment by pragmadash** [comment]
It's okay. Because of event delegation approach, Catberry creates a proxy object for every event appeared on the page. So, it proxies every property of the event object. And in this case, Chrome writes a warning to the console if a deprecated property is accessed.

It won't be a problem in any situation. Just ignore those warnings.

**Comment by wormen** [comment]
I understood it, sometimes just a little pleased when the console unnecessary warnings
