### ISSUE TITLE
this.$context.changed() doesn't work second time in Node

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry#200]
When i call "this.$context.changed()" in handler of store - first time it is working, but second - doesn't.
It is only for this.$context.isServer == true

**Comment by markuplab** [comment]
I think, `changed` must not used during server handle request, because we can't rerender component when streaming html string.

**Comment by slonofanya** [comment]
Sometimes we really need it.
For example: component render himself independently from each other components, which send Action to him (something like, hi i ready to work, please re render).

**Comment by slonofanya** [comment]
Tell me please, when it might be fixed?

**Comment by pragmadash** [comment]
There is nothing to fix here. This is an expected behaviour. The server-side rendering should render a state from URI and it properly does. It does not care about your in-app state changes. That's the point of isomorphic rendering.

It seems like you use store actions in a wrong way. It should be used for sending data to the server not for state changes. The entire state should be described by URI.
