### ISSUE TITLE
document.referrer is ""

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#213]
I opened catberry.org and navigated to other page (browser rendering).

On the second page document.referrer is "", it's ok? I think - no.

If I open SPA vk.com/feed and navigate to vk.com/im and look to referrer I watch "vk.com/feed" 

P.S.: this.$context.referrer - it's work!

**Comment by pragmadash** [comment]
That's reason why `this.$context.referrer` exists. If you open a new tab and type there any address `document.referrer` would be "" including vk.com/feed. The thing is that a browser does not allow to change it somehow due to security reasons. I think you testes something wrong with vk.com, because it should have the same behaviour.
