### ISSUE TITLE
this._foundComponentsByNames.delete is not a function

### ISSUE THREAD

**Issue by chetverikov** [catberry/catberry#284]
In https://github.com/catberry/catberry/blob/develop/lib/finders/ComponentFinder.js#L323-L324 used no existing methods.

If you change the cat component.json will thrown a fatal error:

[2016-05-16T03:55:52.366Z] [FATAL] [catberry:2518] – TypeError: this._foundComponentsByNames.delete is not a function at ComponentFinder._removeComponent

**Comment by pragmadash** [comment]
Thank you so much for finding this!

Unfortunately we still have no unit tests for watching components/stores, therefore such things happen in debug mode.
This particular one I left from the experiment I did for using `Map` type instead of objects but I decided it's not worth it to use polyfill.

I'll fix it ASAP.
