### ISSUE TITLE
Don't remove fragment from URL

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#288]
I have a problem with navigate from `http://catberry.org/documentation?version=master#cat-components` to `http://catberry.org/documentation?version=master`, page don't scroll to up and don't remove fragment from URL

**Comment by reenko** [comment]
Scroll to up fixed, but new url `http://catberry.org/documentation?version=master#`
What you think about removing empty hash '#' ?

**Comment by pragmadash** [comment]
It's impossible to remove the `#` character from the location not using History API or reloading the page. 
In case we use History API we would have the URI in the browser history twice because the framework would put it in the history as well as browser do. 

If we prevented the browser handling the fragment changes at all it would mean that we need to scroll on our own to every element with the ID===fragment and it's not a browser's native behavior. So, this approach is fragile and I would not implement it that way. Another thing is that every browser handles History API usage differently, so it's potentially unstable.

So, it's the only way to implement the stable behavior using fragment identifiers. The presence of `#` character in the location does not affect anything anyway.

Do you have any particular problem having `#` character in the location?

**Comment by reenko** [comment]
No, we haven't problems with '#'
