### ISSUE TITLE
Pluralsight course for CatberryJS?

### ISSUE THREAD

**Issue by overr1de** [catberry/catberry#308]
Hi, Denis. 

Have you ever thought about making a video course for Catberry? It would both encourage people using it and make it more spread and known. For instance, there is still a lack of courses devoted to vuejs on Pluralsight. And it is kind of sad, that only the hyped frameworks get the spotlights in learning materials section.

**Comment by pragmader** [comment]
Hi @overr1de,

Of course I have :)

Unfortunately, I don't have so much time for making a video course according to my life priorities. Not in the near future at least. But I'm open for help and ideas. If we, at least, had some kind of plan/expectations or [implemented examples](https://github.com/catberry/catberry-recipes/issues) for popular use-cases it would be much easier to proceed with the course. That would be the first reason.

The second one is – I'd like to have some contribution from the community as well, because sometimes it seems like I'm the only one who cares about the project and the community does not need another framework but React even if Catberry has some unique technical aspects in comparison, therefore I've stopped investing much efforts into it. 

Personally, I can't accept React as the only tool for developing web-sites and I would use Catberry in my projects but I don't have enough resources to push Catberry or to convince everyone that it's worth to check out. Even if we had a video course it would be really hard to attract people looking at it.

As soon as I see more contribution and interest in the project by the community, I will start dedicating more time working on that. So far, it seems like nobody needs the project being developed.

The only exception – [Flamp.ru](https://flamp.ru), I work with them very close consulting and fixing problems.

**Comment by overr1de** [comment]
Thanks for the response, Denis. Do I get it right that If I (or somebody else) decides to promote the framework by setting up the learning material and organasing an online course at udemy or pluralsight, you won't object such initiative? :)

**Comment by pragmader** [comment]
@overr1de It depends. If the project becomes more popular (to say, would gain more than 1000 stars, or would have more than 15 serious adopters) I will dedicate my time on that. I'm ready to consult new projects and help them developing their projects in the most efficient way.

For instance, the next thing on my roadmap is this feature https://github.com/catberry/catberry/issues/209#issuecomment-250405673

**Comment by pragmader** [comment]
@overr1de BTW, would you help me to create such course?
