### ISSUE TITLE
Page scrolls to top after using browser bac/forward buttons

### ISSUE THREAD

**Issue by ademenev** [catberry/catberry#338]
After pressing browser's back or forward button, the page scrolls to top. That is not what website visitor would expect

To reproduce: open http://catberry.org/, click "Overview". Scroll Overview page to bottom, press back, scroll Main page to bottom, press forward. Now one would expect to see Overview page scrolled to bottom, but it is at top. Now press back - and the Main is also at top

In fact, the whole page state is lost. If there would be a text input on Main page, and I enter some text there, then navigate to Overview, and then press back - that input will be cleared (this can be observed on flamp.ru, for example)

**Comment by reenko** [comment]
@ademenev It's not a bag.
You can see in code [catberry-homepage/catberry_components/pages/index.js:26](https://github.com/catberry/catberry-homepage/blob/a910001084b608d23043b07b4d908f21c2fec86d/catberry_components/pages/index.js#L26), we have `window.scrollTo(0, 0);}` in `unbind`

**Comment by ademenev** [comment]
And what about `catberry init example`? Navigate to commits, then to search, press back, scroll down a bit, press forward, press back - the commits list is at top again, not where it scrolled to

**Comment by ademenev** [comment]
https://judo-heroes.herokuapp.com - that's an example of how I think the things should work in regard of scolling and browser's back/forfard buttons

**Comment by pragmader** [comment]
>That is not what website visitor would expect

What would happen if it was a regular server rendered app? I believe it would be exactly like Catberry behaves, right?

>In fact, the whole page state is lost. If there would be a text input on Main page, and I enter some text there, then navigate to Overview, and then press back - that input will be cleared (this can be observed on flamp.ru, for example)

Same here, if you want to store it somewhere you need to implement this behavior in your components using a `LocalStorage`, for example.

In this particular example, that is an expected behavior because it would work exactly the same in case of a classic server rendered website which people are used to seeing.

This will not change, so if you need another implementation there are many other frameworks/libraries you might like more.

Regarding the state in general, Catberry is an isomorphic framework, all the apps written using Catberry should store any state in URL and decode that state using routes and stores. The only exception off this rule might be an input state while typing, it's suggested to use the `LocalStorage` for that. Once you submit a form, change the URL to have the state (e.g. using the query string in URL), like the commits search example you mentioned does.

**Comment by ademenev** [comment]
> What would happen if it was a regular server rendered app? I believe it would be exactly like Catberry behaves, right?

It would depend on caching-related headers sent by the server. Generally, browser would not reload the page, and display exactly same content, including any values in form inputs

**Comment by pragmader** [comment]
But if you don't scroll to top you can end up with the footer in your viewport which is very confusing for users. In fact, it was an issue from developers reported as a bug to fix this behavior, therefore this code was introduced.

The behavior you're describing is how browsers treat web-sites and it's not under control of an app. When you have a single page application and "change pages" you can't tell a browser to treat as "back" in history, you actually re-render the whole DOM. So, the only option we have here is to pretend it's a page refresh without caching.

**Comment by ademenev** [comment]
Gmail is a relevant example of behavior I am describing. You scroll to to
whatever email you want to see, select it, read it, and after pressing back
you see the list of emails in same scroll position.

I am not saying that current behavior of catberry is "bad". In fact, that
is what observe in many frameworks. I just feel the other behavior I am
talking about would be "nice to have"

Пт, 26 мая 2017 г. в 22:36, Denis Rechkunov <notifications@github.com>:

**Comment by pragmader** [comment]
As I've already mentioned:

>This will not change, so if you need another implementation there are many other frameworks/libraries you might like more.

**Comment by ademenev** [comment]
That should be the whole point of the discussion. Not how things **shoud** behave, but how things framework developers **think** it shoud behave. Just because implementing the other way is beyond of their vision

 I do like catberry, and going to use it in future projects )

**Comment by reenko** [comment]
In Flamp, we save the position in LocalStorage and when the user navigate from feed to review and "back", then we scroll to value from LocalStorage.
