### ISSUE TITLE
Sharing state obtained from external source between client and server

### ISSUE THREAD

**Issue by ademenev** [catberry/catberry#339]
Suppose the following scenario:

In an application, I have an access token to external API, shared between client and server, in a cookie, for example. This token is used by Auth store to obtain information about current user - username, avatar, permissions, etc.

Routes trigger Pages store, passing current route name to it.

There is a navigation component that renders top menu. It uses current route from Pages store to highlight selected menu item. Also, it renders dropdown menu that shows current user's name, avatar, and a set of options depending on user permissions. So, Pages store is made dependant on Auth store, and propagates some data from Auth in its own data.

The Auth store loads user info from API. 

Now comes the problem. When page is initially loaded, it is rendered by the server, and user info is obtained by the server. But when user navigates between pages,  the navigation component is re-rendered. For rendering, it needs data from Auth store, and since there is no cached data for Auth store on the client, the API is queried again from the client.

Is there a way to avoid such duplicate requests, by somehow passing the store data loaded on server to the client side? I mean some mechanism built into the framework iself?

**Comment by pragmader** [comment]
>Is there a way to avoid such duplicate requests, by somehow passing the store data loaded on server to the client side? I mean some mechanism built into the framework iself?

It's a necessary sacrifice. 

In early version of Catberry, the framework served the state object computed on the server-side along with the HTML of the page and then restored the whole state on the client side (like Fluxible does, for instance).

But then it turned out that the page's markup got huge in real world apps and most of the cases people didn't need this state at all. Usually, users just want to have a look at the page and then close it. Another case would be search crawlers – they need just to index the page and therefore the state object was overkill in general. So, we got rid of it completely and introduced this lazy state computation on client-side.

Also, if you think of caching it's much easier to introduce caching in the API service rather then to spend more time serving HTML of the app. When I was working on a big project based on Catberry our numbers showed that the current implementation cause less load then the big HTML pages with state objects.

I'm still sure it was a right decision to make.

**Comment by ademenev** [comment]
Indeed, there is no benefit in sharing state for stores that are going to change or become invalid as user navigates the app. But for stores with data that is not likely to change for all the time the app is open in the browser, it saves at least one API call per store.

Anyway, in the meantime I have implemented this state sharing as a combination of a service and a component.
